### ISSUE TITLE
Interested to see what was changed

### ISSUE THREAD

**Issue by qdevpl** [colistro123/GTAIV_ExtendVidMem#2]
Hi. While I won't complain about free dll that fixes the problem, I wonder if you could expose what was changed by you to make it work, maybe by doing separate commit on other brach. Right now it's all in one commit. 

Why?
-Curiosity
-Someone else might want to maintain this
-Maybe it will give someone an idea how to fix something else with SH2Proxy (easing out entry barrier)

**Comment by colistro123** [comment]
@qdevpl Most of the fundamental code is in the link below, search for `availableVidMem` for clues. I pretty much just hook `GetMaxAvailableVideoMemory` which returns the max available video ram in GTA IV and modify it to return something else. I also create a hook to Direct3DCreate9 to get the D3D device the host application creates and figure out the amount of available VRAM by creating a dummy DXGI adapter.

https://github.com/colistro123/GTAIV_ExtendVidMem/blob/master/SH2Proxy/VCPatcher.cpp#L78
